import type { NextPage } from "next";
import Head from "next/head";
import Footer from "../components/Footer";
import Header from "../components/Header";
import doctor from "../public/doctor.png";

const Home: NextPage = () => {
	return (
		<>
			<div className="max-w-7xl mx-auto font-sans">
				<Head>
					<title>Jord</title>
					<meta name="description" content="Generated by create next app" />
					<link rel="icon" href="/favicon.ico" />
				</Head>

				{/* Navigation */}
				<Header />

				{/* Banner */}
				<div
					className="flex justify-between items-center 
      bg-pink-200 border-y py-10 lg:py-0"
				>
					<div className="px-10 space-y-3">
						<h1 className="text-black text-5xl max-w-xl font-medium">
							<span className="underline decoration-4">Lovecare,</span> the best
							choice for your health and wellness
						</h1>
						<div className="inline-flex">
							<img
								src="https://assets.stickpng.com/thumbs/5a902db97f96951c82922874.png"
								alt="appstore"
								className="w-40"
							/>
							<img
								src="https://www.logo.wine/a/logo/Google_Play/Google_Play-Badge-Logo.wine.svg"
								alt="googleplay"
								className="w-56"
							/>
						</div>
					</div>
					<img
						src={doctor.src}
						alt="doctor"
						className="hidden md:inline-flex h-44 lg:h-full"
					/>
				</div>

				{/* Our Services */}
				<div className="py-20">
					<div>
						<h1 className="text-gray-500 text-center text-6xl">Our Services</h1>
					</div>

					<div className="grid grid-cols-3 gap-2 text-black justify-items-center">
						{/* Card */}
						<div className="m-5 flex items-center w-52">
							<div className="h-52 justify-between cursor-pointer transform translate-y-4 hover:translate-y-0 duration-500 ease-in-out">
								<div className="relative overflow-hidden">
									<img
										src="https://lovecare.id/_next/image?url=https%3A%2F%2Fstorage.googleapis.com%2Fstorage.lovecare.id%2Fsolution-banner-homecare-v2.png&w=256&q=75"
										alt="home"
										className="w-full"
									/>
									<h1 className="font-lg text-center text-lg mr-2">
										Home Care
									</h1>
								</div>
							</div>
						</div>
						<div className="m-5 flex items-center w-52">
							<div className="h-52 justify-between cursor-pointer transform translate-y-4 hover:translate-y-0 duration-500 ease-in-out">
								<div className="relative overflow-hidden">
									<img
										src="https://lovecare.id/_next/image?url=https%3A%2F%2Fstorage.googleapis.com%2Fstorage.lovecare.id%2Fsolution-banner-covid-19-v2.png&w=256&q=75"
										alt="home"
										className="w-full"
									/>
									<h1 className="font-lg text-center text-lg mr-2">
										Home Care
									</h1>
								</div>
							</div>
						</div>
						<div className="m-5 flex items-center w-52">
							<div className="h-52 justify-between cursor-pointer transform translate-y-4 hover:translate-y-0 duration-500 ease-in-out">
								<div className="relative overflow-hidden">
									<img
										src="https://lovecare.id/_next/image?url=https%3A%2F%2Fstorage.googleapis.com%2Fstorage.lovecare.id%2Fsolution-banner-babycare-v2.png&w=256&q=75"
										alt="home"
										className="w-full"
									/>
									<h1 className="font-lg text-center text-lg mr-2">
										Home Care
									</h1>
								</div>
							</div>
						</div>
					</div>
				</div>
        <Footer />
			</div>
		</>
	);
};

export default Home;
